version: "1.0"

services:
  todoapp-be:
    image: todoapp-be:1.0
    restart: unless-stopped
    build:
      context: ./Backend
      dockerfile: ./Dockerfile
    ports:
      - "5110:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:80"

  todoapp-fe:
    image: todoapp-fe:1.0
    restart: unless-stopped
    build:
      context: ./Frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - todoapp-be

  nginx:
    image: nginx:stable
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - todoapp-be
      - todoapp-fe