apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-be-depl
  labels:
    app: todoapp-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp-be
  template:
    metadata:
      labels:
        app: todoapp-be
        tier: backend
        track: stable
    spec:
      containers:
        - name: todoapp-be
          image: todoapp-be:1.0
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80       
---
apiVersion: v1
kind: Service
metadata:
  name: todoapp-be-service
spec:
  selector:
    app: todoapp-be
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP